#!/usr/bin/env node
// Measures the counts that a hand-maintained README rots on, and emits STATUS.md.
//
// The direction review of 2026-08-24 found four false statements in README.md — 1425 tests against
// 2331, fourteen ADRs against fifty, WP-06 "blocked: needs an adopter" when an adopter exists and
// pins a published version, and issue #27 described as open after it closed. None was ever wrong
// when written. Each was true once and nothing recomputed it.
//
// So the numbers are measured here rather than typed. What this cannot measure — whether a
// production path has actually run end to end — is a judgement, and it stays prose in STATUS.md
// under a heading that says so.
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const sh = (cmd, args) => execFileSync(cmd, args, { encoding: "utf8" }).trim();
const quiet = (cmd, args) => {
  try {
    return sh(cmd, args);
  } catch {
    return null;
  }
};

const packages = readdirSync("packages", { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => {
    const manifest = JSON.parse(readFileSync(`packages/${entry.name}/package.json`, "utf8"));
    return { dir: entry.name, name: manifest.name, private: manifest.private === true };
  });
const publicPackages = packages.filter((pkg) => !pkg.private);

const adrs = readdirSync("docs/adr").filter((file) => /^\d{4}-.+\.md$/.test(file));

// Test totals come from the runner, not from counting `it(` — a count of call sites misses
// table-driven cases and would drift from what CI reports, which is the number a reader wants.
const testOutput = quiet("npm", ["test"]) ?? "";
const testTotal = [...testOutput.matchAll(/Tests +(\d+) passed/g)].reduce(
  (sum, match) => sum + Number(match[1]),
  0,
);

const openIssues = quiet("gh", [
  "issue",
  "list",
  "--state",
  "open",
  "--limit",
  "200",
  "--json",
  "number,title",
]);
const issues = openIssues === null ? null : JSON.parse(openIssues);

const distTags = quiet("npm", ["view", "@aldus-runtime/core", "dist-tags", "--json"]);
const tags = distTags === null ? null : JSON.parse(distTags);

const head = sh("git", ["rev-parse", "--short", "HEAD"]);

const unknown = "not measured (no network or `gh` unavailable)";
const out = [];
out.push("# Status");
out.push("");
out.push(
  "<!-- Generated by `node scripts/status.mjs`. Do not edit by hand — see the header there. -->",
);
out.push("");
out.push(`Measured at \`${head}\`.`);
out.push("");
out.push("## Measured");
out.push("");
out.push("| | |");
out.push("| --- | --- |");
out.push(`| public packages | ${publicPackages.length} |`);
out.push(`| private packages | ${packages.length - publicPackages.length} |`);
out.push(`| tests passing | ${testTotal === 0 ? unknown : testTotal} |`);
out.push(`| ADRs | ${adrs.length} |`);
out.push(`| open issues | ${issues === null ? unknown : issues.length} |`);
out.push(`| npm \`latest\` | ${tags === null ? unknown : `\`${tags.latest}\``} |`);
out.push(`| npm \`next\` | ${tags === null ? unknown : `\`${tags.next}\``} |`);
out.push("");
out.push("## Published packages");
out.push("");
for (const pkg of publicPackages) out.push(`- \`${pkg.name}\``);
out.push("");
if (issues !== null) {
  out.push("## Open issues");
  out.push("");
  for (const issue of issues)
    out.push(
      `- [#${issue.number}](https://github.com/jamchen/aldus/issues/${issue.number}) — ${issue.title}`,
    );
  out.push("");
}
out.push("## Not measured, and not measurable here");
out.push("");
out.push(
  "**No adopter production path has run end to end.** Every number above is about this repository," +
    " and none of them is evidence that the Runtime has produced an episode. The direction review" +
    " of 2026-08-24 is explicit that package, ADR and test counts must stop being read as" +
    " completeness, and this section exists so this file cannot be read that way either.",
);
out.push("");
out.push(
  "`latest` currently points at a prerelease. That predates the review and is a known state, not" +
    " a promotion made under it.",
);
out.push("");
writeFileSync("STATUS.md", out.join("\n"));
console.log(
  `STATUS.md written at ${head}: ${publicPackages.length} public packages, ${testTotal} tests, ${adrs.length} ADRs.`,
);
