/**
 * Reconstructability policy and cleanup planning.
 *
 * Contract §8.1 states the rule this module enforces:
 *
 * > Irreplaceable artifacts MUST be archived before disposable working files are cleaned.
 *
 * The ordering is the whole point. A cleanup that runs first and archives afterwards has already
 * destroyed the bytes it was supposed to preserve, and §8 classifies an artifact `irreplaceable`
 * precisely because no re-run recovers it — a paid synthesis take that a human approved (§13.3)
 * exists exactly once.
 *
 * So planning is separate from execution, and execution refuses rather than skips. A cleanup that
 * quietly omitted the blocked files would report success while leaving the operator believing the
 * workspace was tidied; a refusal makes the operator resolve the archive gap deliberately.
 *
 * Nothing here deletes on a schedule. Retention policy (§15.1) is out of scope for WP-03: this
 * reports what retention *would* permit, and a caller decides.
 */

import type { Reconstructability } from "@aldus/core";

import type { ArtifactRecord } from "./record.js";

/** Why a specific artifact may not be cleaned. */
export interface CleanupBlock {
  /** The artifact that cannot be removed. */
  record: ArtifactRecord;
  /** Machine-readable reason. */
  reason: "unarchived-irreplaceable" | "archive-unverified";
  /** Operator-facing explanation. */
  explanation: string;
}

/** What a cleanup would do, decided before anything is removed. */
export interface CleanupPlan {
  /** Artifacts whose working files may be removed. */
  removable: ArtifactRecord[];
  /** Artifacts that must not be removed, with the reason for each. */
  blocked: CleanupBlock[];
  /** Candidate IDs that are not registered at all. */
  unknownArtifactIds: string[];
  /** True when nothing blocks the plan. */
  get safe(): boolean;
}

/**
 * Whether an artifact's bytes must survive the loss of its working file.
 *
 * `source` and `reproducible` may be cleaned freely: a source can be fetched again and a
 * reproducible artifact can be regenerated by re-running the stage that made it. Only
 * `irreplaceable` requires custody first.
 *
 * Note what is deliberately *not* here: nothing treats a recorded provider seed as making an
 * artifact reproducible. Contract §8.1 requires a seed to be recorded but forbids treating it as
 * a reproducibility guarantee, and §1.2 states outright that Aldus does not guarantee a seed
 * reproduces identical audio. A seed is evidence of how something was made, never a licence to
 * delete it.
 */
export function requiresArchiveBeforeCleanup(reconstructability: Reconstructability): boolean {
  return reconstructability === "irreplaceable";
}

/** True if the record holds a receipt strong enough to satisfy §8.1. */
export function isArchived(record: ArtifactRecord): boolean {
  return record.archive !== undefined && record.archive.verified;
}

/**
 * Decide what a cleanup may remove, without removing anything.
 *
 * `candidates` are the artifact IDs a caller proposes to clean — typically the working files of a
 * completed Run. Everything not proposed is simply left alone; this never widens the caller's
 * request.
 */
export function planCleanup(
  candidates: readonly string[],
  records: readonly ArtifactRecord[],
): CleanupPlan {
  const byId = new Map(records.map((record) => [record.artifact.artifactId, record]));
  const removable: ArtifactRecord[] = [];
  const blocked: CleanupBlock[] = [];
  const unknownArtifactIds: string[] = [];

  for (const artifactId of new Set(candidates)) {
    const record = byId.get(artifactId);
    if (record === undefined) {
      unknownArtifactIds.push(artifactId);
      continue;
    }

    if (!requiresArchiveBeforeCleanup(record.artifact.reconstructability)) {
      removable.push(record);
      continue;
    }

    if (record.archive === undefined) {
      blocked.push({
        record,
        reason: "unarchived-irreplaceable",
        explanation:
          `Artifact ${artifactId} is irreplaceable and has not been archived. Contract §8.1 ` +
          "requires irreplaceable artifacts to be archived before disposable working files are " +
          "cleaned, and no re-run recovers these bytes. Archive it, then plan again.",
      });
      continue;
    }

    if (!record.archive.verified) {
      blocked.push({
        record,
        reason: "archive-unverified",
        explanation:
          `Artifact ${artifactId} is irreplaceable and its archive receipt is unverified, so ` +
          "the archive has not confirmed it holds these bytes. An unverified receipt is a " +
          "belief, not custody.",
      });
      continue;
    }

    removable.push(record);
  }

  return {
    removable,
    blocked,
    unknownArtifactIds,
    get safe() {
      return this.blocked.length === 0;
    },
  };
}
